name: Publish dev release

on:
  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install npm packages
        run: npm ci

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: bump version
        run: |
          echo "$(npm pkg get version --prefix packages/framework-webpack | cut -d '"' -f 2 | cut -d '-' -f 1)-dev.$(git rev-parse --short HEAD)" | xargs npm version -w packages/framework-webpack --no-git-tag-version
          echo "$(npm pkg get version --prefix packages/preset-webpack | cut -d '"' -f 2 | cut -d '-' -f 1)-dev.$(git rev-parse --short HEAD)" | xargs npm version -w packages/preset-webpack --no-git-tag-version
          echo "$(npm pkg get version --prefix packages/renderer | cut -d '"' -f 2 | cut -d '-' -f 1)-dev.$(git rev-parse --short HEAD)" | xargs npm version -w packages/renderer --no-git-tag-version

      - name: publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --tag next -w packages/framework-webpack
          npm publish --tag next -w packages/preset-webpack
          npm publish --tag next -w packages/renderer

        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}